# Equivalence of various equiangular samplings

In this demo we show the equivalence between Fejer/Clenshaw-Curtis sampling and other equiangular sampling schemes, including MW, MWSS and DH.

In [1]:
import s2fft 
import numpy as np

JAX is not using 64-bit precision. This will dramatically affect numerical precision at even moderate L.


Set band-limit for tests.

In [2]:
L = 4

## Equivalence of MW and Fejer type 1 sampling

In [3]:
thetas_mw = s2fft.sampling.s2_samples.thetas(L, sampling="mw")

In [4]:
thetas_mw

array([0.44879895, 1.34639685, 2.24399475, 3.14159265])

In [5]:
n = L - 1/2

In [6]:
thetas_mw_fejer1 = (np.arange(0, n) + 0.5) * np.pi / n

In [7]:
thetas_mw_fejer1

array([0.44879895, 1.34639685, 2.24399475, 3.14159265])

In [8]:
assert np.allclose(thetas_mw, thetas_mw_fejer1)

## Equivalence of MWSS and Clenshaw-Curtis (Fejer type 2 with end-points) sampling 

In [9]:
thetas_mwss = s2fft.sampling.s2_samples.thetas(L, sampling="mwss")
thetas_mwss

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [10]:
n = L

In [11]:
thetas_mwss_fejer2 = np.arange(1, n) * np.pi / n

In [12]:
thetas_mwss_fejer2

array([0.78539816, 1.57079633, 2.35619449])

Note that Fejer tyle 2 sampling does not include end-points.

In [13]:
assert np.allclose(thetas_mwss[1:-1], thetas_mwss_fejer2)

In [14]:
thetas_mwss_cc = np.arange(0, n + 1) * np.pi / n

In [15]:
thetas_mwss_cc

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [16]:
assert np.allclose(thetas_mwss, thetas_mwss_cc)

## Equivalence of DH and Fejer type 1 sampling

In [17]:
thetas_dh = s2fft.sampling.s2_samples.thetas(L, sampling="dh")
thetas_dh

array([0.19634954, 0.58904862, 0.9817477 , 1.37444679, 1.76714587,
       2.15984495, 2.55254403, 2.94524311])

In [18]:
n = 2 * L

In [19]:
thetas_dh_fejer1 = (np.arange(0, n) + 0.5) * np.pi / n

In [20]:
thetas_dh_fejer1

array([0.19634954, 0.58904862, 0.9817477 , 1.37444679, 1.76714587,
       2.15984495, 2.55254403, 2.94524311])

In [21]:
assert np.allclose(thetas_dh, thetas_dh_fejer1)